on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master]

name: CI-checks

jobs:
  CI-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
            distribution: 'zulu'
            java-version: '11'
            java-package: jdk 

      - name: Install Nextflow
        run: curl -fsSL get.nextflow.io | bash && mv nextflow /usr/local/bin
      
      - name: Run CI checks
        run: ./ci/ci.sh run && ./ci/ci.sh validate 
        
